server:
  port: 8861
# spring
spring:
  application:
    name: bzz-server-zookeeper
  cloud:
    zookeeper:
      connect-string: 192.168.253.30:2181,192.168.253.31:2181,192.168.253.32:2181
      discovery:
        register: false
      dependency:
        ribbon:
          enabled: false
ribbon:
  eureka:
    enabled: false

